spring.application.name=csv2db


# Datasource configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/springbatch
spring.datasource.username=postgres
spring.datasource.password=dsa321
spring.datasource.driver-class-name=org.postgresql.Driver
 
# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
